name: DeleteObject release

on:
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/release.yml@main
    with:
      workdir: Frends.AmazonS3.DeleteObject
      strict_analyzers: true
    secrets:
      feed_api_key: ${{ secrets.TASKS_FEED_API_KEY }}
