name: DownloadObject_build_test

on:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.AmazonS3.DownloadObject/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.AmazonS3.DownloadObject
      strict_analyzers: true
      env_var_name_1: HiQ_AWSS3Test_AccessKey
      env_var_name_2: HiQ_AWSS3Test_BucketName
      env_var_name_3: HiQ_AWSS3Test_SecretAccessKey
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.HIQ_AWSS3TEST_ACCESSKEY }}
      env_var_value_2: ${{ secrets.HIQ_AWSS3TEST_BUCKETNAME }}
      env_var_value_3: ${{ secrets.HIQ_AWSS3TEST_SECRETACCESSKEY }}
